---
title: "M148 Data Manipulation"
author: "Harry Kim"
date: "2023-02-10"
output: html_document
---

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(lubridate)
```

```{r}
#data <- read.csv("week1log.csv")
```

```{r}
data <- read.csv("datanew.csv")
```

```{r}
colnames(data)
```

```{r}
## evar23, visitoridlow, visitoridhigh = 348769
## evar23, visitdatetime = 4345985
## evar23, visitstarttimegmt = 278548

## prop29 = maturity
top <- head(data, 100000)
```

```{r}
start <- as_datetime(min(data$hit_time_gmt))
end <- as_datetime(max(data$hit_time_gmt))
```

```{r}
grouped <- data %>% group_by(cookieid, visitnumber) %>%
  filter(cookieid != 0) %>%
  summarise(logs = n(), # Number of entries / logs per visitor
            # User Info
            
            userid = first(evar23[!is.na(evar23)]),
            device = first(devicetype),
            city = first(geocity),
            state = first(georegion),
            payment = max(paymentmethod), # Assumes a single payment method
            
            # Number of visits made by the user
            numvisits = max(visitnumber),
            
            promocode_used = max(promocode), # Assumes a single promocode
            num_promocode_tried = sum(evar16 > 0),
            found_workingpromo = any(promocode > 0),
            
            maturity = max(evar28),
            
            #Login action happened
            login = (any(is.na(evar23)) & any(!is.na(evar23))),
            noid = all(is.na(evar23)),
            
            #Date
            localtime = first(str_extract(as_datetime(visitstarttimegmt), "(\\d{2}:\\d{2}:\\d{2})")),
            morning = (as.numeric(str_extract(localtime, "(^\\d{2})")) >= 0 & as.numeric(str_extract(localtime, "(^\\d{2})")) < 6),
            day = (as.numeric(str_extract(localtime, "(^\\d{2})")) >= 6 & as.numeric(str_extract(localtime, "(^\\d{2})")) < 18),
            night = (as.numeric(str_extract(localtime, "(^\\d{2})")) >= 18 & as.numeric(str_extract(localtime, "(^\\d{2})")) < 24),
            
            #Action Added to Cart and Place Order
            AddtoCartTRUE = as.logical( sum( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,")) ),
            OrderTRUE = as.logical(sum(ordernumber > 0)), # TRUE if ordered FALSE else
            RemoveItemTRUE = as.logical( sum( str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,")) ),
            CheckOutInitiateTRUE = as.logical( sum( str_detect(clickaction, "Check Out Now") | str_detect(eventlist, ",11,")) ),
            
            PlaceOrder = sum( str_detect(clickaction, "Place Order")),
            AddtoCart = sum( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,")),
            RemoveFromCart = sum(str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,")),
            NumberofOrder = sum(ordernumber > 0), # Number of orders ~ Number of Order Numbers
            CheckOutInitiated = sum( str_detect(clickaction, "Check Out Now") | str_detect(eventlist, ",11,")),
            
            ViewCart = sum(str_detect(eventlist, ",14,")), # Eventlist view cart
            CartOpen = sum(str_detect(eventlist, ",10,")), # Eventlist cart open
            Clicks = sum(clickactiontype %in% c("2","3")), # Total number of clicks made
            
            # Time
            firstaddcart.timestamp = hit_time_gmt[first( which(str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,")))],
            firstplaceorder.timestamp = hit_time_gmt[first( which( str_detect(clickaction, "Place Order") ))],
            firstrmvcart.timestamp = hit_time_gmt[first( which(str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,") ))],
            shopduration = (max(hit_time_gmt) - first(visitstarttimegmt)),
            firstaddcart = -(first(visitstarttimegmt - first(firstaddcart.timestamp))),
            firstplaceorder = -(first(visitstarttimegmt - first(firstplaceorder.timestamp))),
            firstrmvcart = -(first(visitstarttimegmt - first(firstrmvcart.timestamp))),
          
            firstaddtocart = first(category[which(pageeventvar2 == 'scAddPDP')-1]),
            checkedout = max(str_detect(pageeventvar2,'checkout') | str_detect(pageeventvar2,'Checkout')),
            
            # First recorded log/entries of adding an item to cart
            log.firstaddcart = first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )),
            # First recorded log/entries of placing an order
            log.firstplaceorder = first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )),
            # The number of log between first add cart and first place order
            log.carttoorder = first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )) - first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )),
            # First recorded log/entries of removing an item from cart
            log.firstremoveitem = first(which( str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,"))),
            
            # Page Log
            CheckoutConfirm.Page = sum(str_detect(pagename,"checkout:confirmation")), # checks if checkout confirmation page was visted
            Clearance.Page = sum(str_detect(pagename, ":Clearance")), # Checks if the clearance page was visited
            
            log.addcart.prop = ( first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )) / n() ),
            log.placeorder.prop = ( first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )) / n() ),
            
            # Search Data
            search_initated = any(searchterms > 0),
            search_word_length = length(unlist(strsplit(searchterms, split = ""))),
            
            # Finding Methods
            searchTRUE = any(productfindingmethods == "Search"),
            browseTRUE = any(productfindingmethods == "Browse"),
            widTRUE = any(productfindingmethods == "wid"),
            
            Numsearch = sum(productfindingmethods == "Search"),
            Numbrowse = sum(productfindingmethods == "Browse"),
            Numwid = sum(productfindingmethods == "wid"),
           
            .groups = 'drop'
           )
```

```{r}
useronly <- grouped %>% filter(!noid)
```


```{r}
# Export Code
write.csv(useronly, "userdata2.csv")
```


```{r}
check <- top %>% group_by(cookieid) %>% filter(cookieid != 0) %>% summarise(unique = length(unique(visitnumber)),
                                                                            userid = max(evar23),
                                                                                   searchTRUE = any(productfindingmethods == "Search"),
                                                                                    browseTRUE = any(productfindingmethods == "Browse"),
                                                                                    widTRUE = any(productfindingmethods == "wid"))

checkcart <- top[(top$evar23 == 3563970941) & !is.na(top$evar23) ,]

check <- top[(top$evar23 == 3945456840) & !is.na(top$evar23),]
check_count <- check %>% group_by(visitoridhigh, visitoridlow) %>% summarise(n = n())
check_count1 <- check %>% group_by(cookieid) %>% summarise(n = n())

check1 <- top %>% group_by(visitoridhigh, visitoridlow) %>% summarise(n = n())
check2 <- top %>% group_by(cookieid) %>% summarise(n = n())
```


"eventlist"

14 - Cart View
12 - Cart Addition
13 - Cart Remove
11 - Checkout
10 - Cart Open

```{r}
webdata <- data %>% 
  group_by(cookieid) %>% 
  summarise(logs = n(), # Number of entries / logs per visitor
            visitnumber = max(visitnumber), # Maximum value for visit number
           
            # User Info
            device = first(devicetype),
            city = first(geocity),
            state = first(georegion),
            payment = max(paymentmethod), # Assumes a single payment method 
            promocode = max(promocode), # Assumes a single promocode
            opentobuy = max(opentobuy),
            
            # Time
            
            # User Action                                                           
            AddtoCart = sum( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,")),
            RemoveFromCart = sum(str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,")),
            PlaceOrder = sum( str_detect(clickaction, "Place Order")),
            NumberofOrder = sum(ordernumber > 0), # Number of orders ~ Number of Order Numbers
            CheckOutInitiated = sum( str_detect(clickaction, "Check Out Now") | str_detect(eventlist, ",11,")),
            
            ViewCart = sum(str_detect(eventlist, ",14,")), # Eventlist view cart
            CartOpen = sum(str_detect(eventlist, ",10,")), # Eventlist cart open
            Clicks = sum(clickactiontype %in% c("2","3")), # Total number of clicks made
                                                                       
            # User Action Boolean (Boolean version of User Action)                                                           
            AddtoCartTRUE = as.logical( sum( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,")) ),
            PlaceOrderTRUE = as.logical( sum( str_detect(clickaction, "Place Order"))),
            OrderTRUE = as.logical(sum(ordernumber > 0)), # TRUE if ordered FALSE else
            RemoveItemTRUE = as.logical( sum( str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,")) ),
            CheckOutInitiateTRUE = as.logical( sum( str_detect(clickaction, "Check Out Now") | str_detect(eventlist, ",11,")) ),
            
            # Page Log
            CheckoutConfirm.Page = sum(str_detect(pagename,"checkout:confirmation")), # checks if checkout confirmation page was visted
            Clearance.Page = sum(str_detect(pagename, ":Clearance")), # Checks if the clearance page was visited
            
            # Log Difference
            
            # First recorded log/entries of adding an item to cart
            log.firstaddcart = first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )),
            # First recorded log/entries of placing an order
            log.firstplaceorder = first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )),
            # The number of log between first add cart and first place order
            log.carttoorder = first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )) - first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )),
            # First recorded log/entries of removing an item from cart
            log.firstremoveitem = first(which( str_detect(clickaction, "Remove Item") | str_detect(eventlist, ",13,"))),
            
            # The proportion logs it took to complete an action to the total number of logs
                # 0.5 would mean that the action, say add to cart, happened during the middle of their stay.
            log.addcart.prop = ( first(which( str_detect(clickaction, "Add to Cart") | str_detect(eventlist, ",12,") )) / n() ),
            log.placeorder.prop = ( first(which( str_detect(clickaction, "Place Order") | str_detect(eventlist, ",11,") )) / n() ))
            
```

```{r}
# Export Code
write.csv(webdata, "grouped.csv")
```

